### ISSUE TITLE
No `current_app` feature.

### ISSUE THREAD

**Issue by gravypod** [mgriley/diva#1]
Hello. I've started playing around with using this library for some data visualization. My codebase was getting a bit too large for a single file. I noticed that this project does not support the `current_app` import that Flask exposes. In Flask you can split your poject into multiple files by importing `current_app` and using that as a substitute for `app.`.

Would this be something that you could implement as well? 

Thanks.

**Comment by mgriley** [comment]
Good idea, I added an "extend" method to the Diva class that should help. You'll need to install diva version 0.1.5 with pip. Here is the new section of the docs: http://diva.readthedocs.io/en/latest/users_guide.html#splitting-into-multiple-files
Please let me know if this is works for you.

**Comment by gravypod** [comment]
Thanks @mgriley. I've tested this out and it works. I might open a few more feature requests that are just creature comfort things. This is a really cool project!

Thanks for all of the hard work.
